import "@total-typescript/ts-reset";
import { AuthProvider } from "@/Providers/AuthProvider"
import Link from "next/link";
import { LogoutButton } from "./LogoutButton";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>
          <header>
            <nav>
              <Link href="/login">Login</Link>
              <LogoutButton />
            </nav>
          </header>
          {children}
        </body>
      </AuthProvider>
    </html>
  )
}
